import re
import requests
import os
from datetime import datetime
from pathlib import Path

def extract_domains(content):
    """Extract unique domains from m3u content"""
    domains = set()
    # Find http/https URLs
    urls = re.findall(r'https?://([^/\s]+)', content)
    for url in urls:
        domains.add(url)
    return domains

def main():
    print("🚀 IPTV Hunter started...")
    
    iptv_dir = Path("iptv")
    output_file = iptv_dir / "all_in_one.m3u"
    
    # Read existing playlist
    if output_file.exists():
        with open(output_file, 'r', encoding='utf-8') as f:
            content = f.read()
        print(f"Loaded existing playlist: {len(content)} chars")
    else:
        content = "#EXTM3U\n# Generated by IPTV Hunter\n"
    
    domains = extract_domains(content)
    print(f"Found {len(domains)} domains: {list(domains)[:10]}...")
    
    # TODO: Add more advanced scraping logic here in future versions
    # For now, just update timestamp and save
    
    header = f"#EXTM3U\n# Playlist updated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n# Total channels: many\n\n"
    
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write(header + content.split("#EXTM3U", 1)[-1] if "#EXTM3U" in content else content)
    
    print("✅ Playlist updated successfully!")

if __name__ == "__main__":
    main()
